version: '3.3'
services:
  api:
    container_name: ewally_api_container
    build: .
    image: ewally
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/ewally-challenge/dist
    ports:
      - "8080:8080"