version: '3.3'
services:
  api:
    container_name: api_container
    image: node:16
    working_dir:  /usr/src/app
    restart: always
    command: bash -c  "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    ports:
      - "5050:5050"